name: Elixir Tests

on:
  pull_request:
    branches:
      - master # Or your default branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.15"
          otp-version: "26"

      - name: Install dependencies
        run: mix deps.get

      - name: Compile project
        run: mix compile --warnings-as-errors

      - name: Run tests
        env:
          MIX_ENV: test
        run: mix test
